[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = "true"

[tasks.ci-build]
command = "cargo"
args = ["build", "-vv", "--all-features"]

[tasks.ci-test]
command = "cargo"
args = ["test", "-vv", "--all-features"]
dependencies = ["ci-build"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clippy]
install_crate = "clippy"
command = "cargo"
args = ["clippy"]

[tasks.clean]
command = "cargo"
args = ["clean"]
