[package]
name = "ast"
version = "0.0.1"
authors = ["Roee Shapira <roy.shap1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
