name: Clippy Check

on:
  push:
    paths:
      - "**/*.rs"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - run: cargo clippy
